require("Scripts.Control.DayNightCycle")
require("Scripts.Control.EnrichedRecipeEnable")
require("Scripts.Control.MagicField")
require("Scripts.Control.ExlusiveTechnologies")
require("Scripts.Control.GlassMachinesBreak")
